Repository DSM-ROC/DSM-ROC_Backend, pull requests merged in 2022-12, with the labels that each got.

#45 merge(#44): CI 설정
  .eslintrc
  .github/workflows/ROC-CI.yml
  src/controllers/challenge.controller.ts
  src/controllers/user.controller.ts
  src/entity/challenge.ts
  src/entity/enum/topic.enum.ts
  src/entity/join.ts
  src/entity/user.ts
  src/middlewares/verifyToken.ts
  src/repositories/challenge.repository.ts
  src/repositories/join.repository.ts
  src/repositories/user.repository.ts
  src/routes/challenge.router.ts
  src/routes/index.ts
  src/routes/user.router.ts
  src/services/challenge.service.ts
  src/services/user.service.ts
Labels: chore, feat

#46 merge(#43): entity 수정
  src/entity/challenge.ts
  src/entity/comment.ts
  src/entity/like.ts
  src/entity/post.ts
  src/entity/review.ts
  src/entity/user.ts
  src/ormconfig.ts
  src/repositories/join.repository.ts
  src/repositories/review.repository.ts
Labels: chore

#49 merge(#43): 하루 리뷰 생성 api 추가
  src/controllers/review.controller.ts
  src/controllers/user.controller.ts
  src/entity/review.ts
  src/ormconfig.ts
  src/routes/index.ts
  src/routes/review.router.ts
  src/services/review.service.ts
Labels: feat

#51 merge(#43): 하루 리뷰 전체 조회 api 추가
  src/controllers/review.controller.ts
  src/repositories/review.repository.ts
  src/routes/review.router.ts
  src/services/review.service.ts
Labels: feat

#52 merge(#43): 특정 리뷰 조회 api 추가
  src/controllers/review.controller.ts
  src/repositories/review.repository.ts
  src/routes/review.router.ts
  src/services/review.service.ts
Labels: feat

#53 feat(#35): 내가 가입한 challenge 목록 조회 api 추가
  src/controllers/challenge.controller.ts
  src/repositories/join.repository.ts
  src/routes/challenge.router.ts
  src/services/challenge.service.ts
Labels: feat

#54 feat(#35): challenge 멤버 보기 api 수정
  src/controllers/challenge.controller.ts
  src/entity/challenge.ts
  src/repositories/challenge.repository.ts
  src/routes/challenge.router.ts
  src/services/challenge.service.ts
  src/shared/DataTransferObject.ts
Labels: feat

#55 feat(#35): challenge 기간 설정 기능 수정
  src/entity/challenge.ts
  src/repositories/challenge.repository.ts
  src/services/challenge.service.ts
  src/shared/DataTransferObject.ts
Labels: feat

#56 feat(#43): review 날짜 검사 api 추가
  src/controllers/review.controller.ts
  src/services/review.service.ts
Labels: feat

#58 feat(#53): 게시글 작성 api 추가
  src/controllers/post.controller.ts
  src/repositories/post.repository.ts
  src/services/post.service.ts
Labels: feat

#59 update(#43): review service 수정
  src/services/review.service.ts
Labels: feat

#60 feat(#35): challenge 탈퇴 기능 추가
  src/controllers/challenge.controller.ts
  src/repositories/challenge.repository.ts
  src/repositories/join.repository.ts
  src/routes/challenge.router.ts
  src/services/challenge.service.ts
Labels: feat

#61 update(#43): review api 수정
  src/repositories/review.repository.ts
  src/services/review.service.ts
Labels: feat

#62 update(#43): review 관련 api 수정
  src/repositories/review.repository.ts
  src/services/review.service.ts
Labels: feat

#65 update(#53): 게시글 작성 api 추가
  src/controllers/post.controller.ts
  src/controllers/review.controller.ts
  src/repositories/post.repository.ts
  src/routes/index.ts
  src/routes/post.router.ts
  src/services/post.service.ts
Labels: feat

#67 merge(#66): 유저 정보 불러올 때 password 불러오지 않도록 수정
  src/repositories/user.repository.ts
Labels: bug, fix

#68 feat(#53): 게시글 수정 api 추가
  src/controllers/post.controller.ts
  src/routes/post.router.ts
Labels: feat

#70 feat(#53): 게시글 전체 조회 기능 추가
  src/controllers/post.controller.ts
  src/routes/post.router.ts
Labels: feat

#71 update(#53): post 관련 수정
  src/entity/post.ts
  src/repositories/post.repository.ts
  src/services/post.service.ts
Labels: feat

#72 update(#43): review 관련 기능 수정
  src/repositories/review.repository.ts
  src/services/review.service.ts
Labels: feat

#73 update(#53): 댓글기능 폴더 초기 설정
  src/controllers/comment.controller.ts
  src/repositories/comment.repository.ts
  src/routes/comment.router.ts
  src/services/comment.service.ts
Labels: chore

#74 (#53): 댓글 작성 기능 추가
  src/controllers/comment.controller.ts
  src/entity/comment.ts
  src/routes/comment.router.ts
  src/routes/index.ts
  src/services/comment.service.ts
  src/services/post.service.ts
Labels: feat

#76 update(comment): 댓글 수정 기능 추가
  src/controllers/comment.controller.ts
  src/repositories/comment.repository.ts
  src/routes/comment.router.ts
  src/services/comment.service.ts
Labels: feat

#77 update(comment): 댓글 삭제 기능 추가
  src/controllers/comment.controller.ts
  src/routes/comment.router.ts
Labels: feat

#79 merge(#78): timezone 설정
  package.json
  src/config/database-config.ts
  src/config/index.ts
  src/ormconfig.ts
Labels: feat

#80 feat(#53): 게시글 좋아요 기능 추가
  src/controllers/like.controller.ts
  src/controllers/post.controller.ts
  src/repositories/comment.repository.ts
  src/repositories/like.repository.ts
  src/routes/index.ts
  src/routes/like.router.ts
  src/services/challenge.service.ts
  src/services/like.service.ts
  src/services/post.service.ts
Labels: feat

#81 feat(upload): 챌린지 커버이미지 설정 기능 추가
  package.json
  src/controllers/challenge.controller.ts
  src/entity/challenge.ts
  src/repositories/challenge.repository.ts
  src/repositories/upload.repository.ts
  src/routes/challenge.router.ts
  src/services/challenge.service.ts
  yarn.lock
Labels: feat

#83 merge(#82): 프론트 요구사항 반영
  src/repositories/challenge.repository.ts
  src/repositories/join.repository.ts
  src/repositories/review.repository.ts
Labels: feat

#85 merge(#84): 검색하기에서 빈배열 반환 에러
  src/repositories/challenge.repository.ts
Labels: bug, fix

#87 merge(#86): 마이페이지 내 정보 보기 API
  src/controllers/user.controller.ts
  src/repositories/user.repository.ts
  src/routes/user.router.ts
  src/services/user.service.ts
  src/shared/DataTransferObject.ts
Labels: feat

#89 merge(#88): 로그아웃 API
  src/constants/auth.ts
  src/controllers/user.controller.ts
  src/routes/user.router.ts
Labels: feat

#91 merge(#90): 유저 탈퇴가 처리되지 않는 현상 해결(cascade와 ondelete)
  src/controllers/user.controller.ts
  src/entity/challenge.ts
  src/entity/comment.ts
  src/entity/join.ts
  src/entity/like.ts
  src/entity/post.ts
  src/entity/review.ts
  src/entity/user.ts
Labels: bug, feat, fix

#93 merge(#92): repository query 수정
  src/repositories/join.repository.ts
Labels: feat, fix

#95 merge(#94): 메소드 변경 및 메소드 네이밍 수정
  src/repositories/like.repository.ts
  src/routes/post.router.ts
  src/services/post.service.ts
Labels: bug, fix

#97 merge(#96): 에러 메시지 좀 더 보기 편하게 수정
  src/loaders/express.ts
  src/routes/challenge.router.ts
  src/routes/index.ts
  src/routes/post.router.ts
  src/routes/review.router.ts
  src/services/challenge.service.ts
  src/services/comment.service.ts
  src/services/like.service.ts
  src/services/post.service.ts
  src/services/review.service.ts
  src/services/user.service.ts
  src/shared/exception.ts
Labels: fix, refactor

#99 merge(#98): 불필요한 import문 삭제 및 리팩토링
  .mock.env
  LICENSE
  README.md
  src/controllers/challenge.controller.ts
  src/entity/post.ts
  src/entity/review.ts
  src/middlewares/verifyToken.ts
  src/repositories/challenge.repository.ts
  src/repositories/upload.repository.ts
  src/routes/challenge.router.ts
  src/routes/comment.router.ts
  src/shared/exception.ts
Labels: refactor

#101 merge(#100): VARCHAR -> TEXT 타입으로 변경
  src/entity/challenge.ts
  src/entity/comment.ts
  src/entity/post.ts
  src/entity/review.ts
Labels: refactor

#103 merge(#102): timestamp 한국시간대로 반환 안되는 문제 해결
  src/entity/challenge.ts
  src/entity/comment.ts
  src/entity/post.ts
  src/entity/review.ts
  src/entity/user.ts
  src/loaders/express.ts
Labels: fix, refactor
